#define ADD_RX_RY 0
#define SUB_RX_RY 1
#define SSP_V 2
#define INC_RX 3
#define DEC_RX 4
#define NEG_RX 5
#define NOT_RX 6
#define AND_RX_RY 7
#define OR_RX_RY 8
#define LOD_V_ADR 9
#define STR_V_MADR 10
#define LOD_MADR_RX 11
#define STR_RX_MADR 12
#define LOD_RX_ADR 13
#define LOD_ACR_RX 14
#define LOD_ACR_ADR 15
#define STR_ACR_MADR 16
#define STR_IC_MADR 17
#define JMP_ADR 18
#define JMP_X 19
#define JMPZ_X 20
#define JMPN_X 21
#define JMPO_X 22
#define HLT 23
#define BREAK 24